name: Build LaTeX document
run-name: Building document
on:
  push:
    tags:
      - v*
      - '!v*.*.*'
jobs:
  Build-LaTeX:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone and get figures
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true

      - name: Set up Git repository
        uses: actions/checkout@v3

      - run: rclone copy OneDriveReadonly:UCL/Thesis/src/figures ${{ github.workspace }}/src/figs
      - run: rclone copy OneDriveReadonly:UCL/Thesis/src/draft_figures ${{ github.workspace }}/src/draft_figs
      - run: ls ${{ github.workspace }}/src/*figs

      - name: Create an integrated figs source file
        run: echo "\\PassOptionsToPackage{disable}{endfloat}" > src/Main-with-figs.tex && cat src/Main.tex >> src/Main-with-figs.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Main.tex
            Main.tex
            Main-with-figs.tex
            Main-with-figs.tex
          working_directory: src/
          args: '-pdf -file-line-error -interaction=nonstopmode -f'
          continue_on_error: true
        continue-on-error: true

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: src/Main*.pdf
